version: '2'

services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./nginx_log:/var/log/nginx
        networks:
            - code-network
        container_name: nginx
    php:
        image: php:5-fpm-alpine
        restart: unless-stopped
        volumes:
            - ./code:/code
            - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - code-network
        container_name: php
networks:
    code-network:
        driver: bridge
